dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh | bash
notifications:
  slack:
    rooms:
      secure: "BktU6+X75ob5ax75SH3Kl12kFYsTFKWrgnGJkJXQyQKAtioFgj6LdHXlNO3+ig2nYzm2dKp+GUgtFnUqw75MRGJnFGr1kscuwI4ErqFqOgaovMDs07kXv9aCODrPu1pbJ/U0+whIyTMuufQNh8oxTHsus/wIOdRqJtOTOwqElRdVFGhkWBS6COKi0q9rg/M1vpuSvvDNLr+Ots5GlCjXEc4v3THr9NZKZnjFWamdzU6W5ATM5BfQev+PMGeDBMgzcVJFDx4M+7oPegHatQD0lbRBbt3Uvf1YHlcwO71bm3PRqPMroneVVfugljr24/TyoCTPmMm4Tuqpov+1DBAv2GIM+TaPjaKUDE4TI6M+CGUGGmJd9ONd93wwlxN6xeYS8alB5sNgaCVGO6aAqfWtTUFKD1VASfItfh1QrcvRJN5K6uD9M2LO1l3aUxROQ6ZkXhFV2ZNwVAleCA0t0LtIalpS64i7poVViz62J6fZpQbwCN7Z+v3znsv5j0O6+hLmufDfIJZbD3TsMnKfte5AE/MaT0xi/vbY1wFOTWASanptAgka9Xh2ZbP0rd4iRRc5tHcgVjFr/lDhqx8BaRYkOewsf0tGsvcaS8kd27vUZS/90PoVVucB5NEDAaV8zBPGFq3IoNHygpReGW2aR9pKjRPLS8qOWavmJvaM3WuLeVU="
