dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
devops-team-otus:aO5TaFBvv9GA1oRqEfjtpHIK#sergey_reshetnikov:
  secure: B6URnqQ92pE6Z5iQPzdm6zs0nIcLMOe4l0S/ZkP5TkokA0hSKR1asnIcnWK2V7uSm3nuBZDn6nI9Vw0+DhyTZrjkBUAP0Kfp93hDYqVRtkywHU5vAPLGN6fYJcmbERCajfFLZUPvPn7TZ1HKmW338DmdEhDU3+Poh562YcLS1pfQzMOrPXTW++F4wW2syf/LQdB2qrJ/L3T94R+mPnBH9xq54xe+LPBleQHC3VtSKcwf3HHQTpsBMy2cWkQra4Se9fzrcUQerPmgi3gQ+HJjsDdqa3By+U6DlnSrCz/EoF5PDhxko2NRy7MO3Iess/RD5zxmqP4G3TxnzPizFZ9yydJn3TJeJ+StJM+9nvUFJaEmpBpJC7bhhFbj5w4W8Scw4hnCsVqJbjAsnWqRysnDuf9dCfHIh46UJhZoeF9E6X6yCu7+5yCD1lw0W378eBG6Jk7omIUS98kO04bo9kLUPgGDZ5nzoE6pBrxpICjAN0DsaBWtyx1pnU1mZRLQrbuz9nOk5OqxFr+qS3GKY6pOEvC4lHA/DAYz22laNeTN4rFIkc2JmErd62MRv/I27JzKm+AzzRcisLhN5pR8Gh/uYW0axaQrQGRTGmpX3VVBJifFavFFYrOAeL4yzmLYCZlF4OWvcpNnGfM5vDFv6pwCjznu880PA6nx8d6N41CzI3c=
