dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
 slack:
  rooms:
   secure:
g5sJ55KFmnBOietKdjPf6YmnpTDJTn9G45wrS93CNYha1YrbyduPnH6XklEc6n9hqeLzLFdDRixgv2LA4ZoCXD2XwDa/qYKcP4QjPfyjWZFA0yQ0EYEpSLFhZ5R57GyeOeIRk5IOmzqlp4FtrAYpmym+nNwRafztvgnlo+4qes5TTuOK/TBWroOuN+Hsm+zBkoRme/YYFxXCANPZsDnnGRvc4b0MgkcQQNdkPz7fmk+duvoE23kybi9x+Uhn92Jomiz3oCZh/LxEiVxxoG05KELWg6G7zg8A8UQdBMyGtTjwGgvtbkwehMVxeR/NXH5endhX8aZ6fpPsR0RGDxB9BqNJSdyfTnSNxe3zPF/l3xMEu7l1byvwsDfcLCpMnf6nWX2nGsctpgC9ejV8YTHqiqlsSUXYM29Uf+WX836nLFJcgyUIwXkwCU3ABoFNN+pX7V+Qgs0BBKWUJhKnUH4YLpBB64/HroQsItJDFXCKoCaiHMPm7FRbsZnPrUTl6/UZbruQalfnmMorsUXbbHEMtwUfs+iIgXTRP4hDYmMFK11v0bC6fwm+VyEmSXXthtVU0ozWEm9v/euhoa1H9gPvFrBNZK1lpyQ5Ob2Bmj95/cFNtU/nIeMZcWWtPHJ/rpldeeCjz56Nym0P0NP1rv53fV2Zb5tOVbb8Ze8GM6xSRuc=
